binaerpiloten_freizeitbooking_plattform_homepage:
    pattern:  /
    defaults: { _controller: BinaerpilotenFreizeitbookingPlattformBundle:Default:index }

gokartlist:
    pattern: /gokart/{regionURLName}
    defaults: { _controller: BinaerpilotenFreizeitbookingPlattformBundle:Default:gokartList }

gokartdetails:
    pattern: /gokart/{regionURLName}/details/{id}
    defaults: { _controller: BinaerpilotenFreizeitbookingPlattformBundle:Default:gokartDetails }

paintballlist:
    pattern: /paintball/{regionURLName}
    defaults: { _controller: BinaerpilotenFreizeitbookingPlattformBundle:Default:paintballList }

paintballdetails:
    pattern: /paintball/{regionURLName}/details/{id}
    defaults: { _controller: BinaerpilotenFreizeitbookingPlattformBundle:Default:paintballDetails }

lasertaglist:
    pattern: /lasertag/{regionURLName}
    defaults: { _controller: BinaerpilotenFreizeitbookingPlattformBundle:Default:lasertagList }

lasertagdetails:
    pattern: /lasertag/{regionURLName}/details/{id}
    defaults: { _controller: BinaerpilotenFreizeitbookingPlattformBundle:Default:lasertagDetails }

lasertagprovider:
    resource: "@BinaerpilotenFreizeitbookingPlattformBundle/Controller/LasertagProviderController.php"
    type: annotation

gokartprovider:
    resource: "@BinaerpilotenFreizeitbookingPlattformBundle/Controller/GokartProviderController.php"
    type: annotation

paintballprovider:
    resource: "@BinaerpilotenFreizeitbookingPlattformBundle/Controller/PaintballProviderController.php"
    type: annotation

region:
    resource: "@BinaerpilotenFreizeitbookingPlattformBundle/Controller/RegionController.php"
    type: annotation

category:
    resource: "@BinaerpilotenFreizeitbookingPlattformBundle/Controller/CategoryController.php"
    type: annotation

seotext:
    resource: "@BinaerpilotenFreizeitbookingPlattformBundle/Controller/SEOTextController.php"
    type: annotation
