binaerpiloten_freizeitbooking_plattform_homepage:
    pattern:  /
    defaults: { _controller: BinaerpilotenFreizeitbookingPlattformBundle:Website:index }

gokartlist:
    pattern: /gokart/{regionURLName}
    defaults: { _controller: BinaerpilotenFreizeitbookingPlattformBundle:Website:gokartList }

gokartdetails:
    pattern: /gokart/{regionURLName}/details/{id}
    defaults: { _controller: BinaerpilotenFreizeitbookingPlattformBundle:Website:gokartDetails }

paintballlist:
    pattern: /paintball/{regionURLName}
    defaults: { _controller: BinaerpilotenFreizeitbookingPlattformBundle:Website:paintballList }

paintballdetails:
    pattern: /paintball/{regionURLName}/details/{id}
    defaults: { _controller: BinaerpilotenFreizeitbookingPlattformBundle:Website:paintballDetails }

lasertaglist:
    pattern: /lasertag/{regionURLName}
    defaults: { _controller: BinaerpilotenFreizeitbookingPlattformBundle:Website:lasertagList }

lasertagdetails:
    pattern: /lasertag/{regionURLName}/details/{id}
    defaults: { _controller: BinaerpilotenFreizeitbookingPlattformBundle:Website:lasertagDetails }

squashlist:
    pattern: /squash/{regionURLName}
    defaults: { _controller: BinaerpilotenFreizeitbookingPlattformBundle:Website:squashList }

squashdetails:
    pattern: /squash/{regionURLName}/details/{id}
    defaults: { _controller: BinaerpilotenFreizeitbookingPlattformBundle:Website:squashDetails }

binaerpiloten_freizeitbooking_plattform_admin:
    resource: "@BinaerpilotenFreizeitbookingPlattformBundle/Resources/config/routing-admin.yml"
    prefix:   /admin
