parameters:
#    binaerpiloten_freizeitbooking_plattform.example.class: Binaerpiloten\FreizeitbookingPlattformBundle\Example

services:
#    binaerpiloten_freizeitbooking_plattform.example:
#        class: %binaerpiloten_freizeitbooking_plattform.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
